### ISSUE TITLE
I Wrote Python Script to Automate Uploading Clipping 

### ISSUE THREAD

**Issue by skillhacker-code** [mammuth/kindle-clippings#47]
Hi , 

I wrote a script to automate the uploading process because I find it really tiring to update the clipping everytime . 

so I wrote this script today . I am sharing because it may help you (uploaded as text because upload as .py is not supported by GitHub). 

Need Python , Selenium 

[kindleUpload.txt](https://github.com/mammuth/kindle-clippings/files/9125460/kindleUpload.txt)

**Comment by mammuth** [comment]
Ah, interesting! Good job 💪 

Personally, I don't find it that cumbersome, though. I just upload it every couple of months.

**Comment by skillhacker-code** [comment]
I am new to programming and I thought this an interesting problem to solve because I update the kindle highlights every week(planning to).

I didn't understand what did you mean by Auth + Upload request Without Selenium.

Thank you so much for Creating this website (I actually donated $5 about a week ago)

**Comment by mammuth** [comment]
When you check the network tab in the Dev tools when signing in and uploading a file, you see the http requests that are being made. 

One could send just these two requests with python instead of doing browser automation. But I just wanted to share it, your little tool works like a charm, too! :muscle:

**Comment by skillhacker-code** [comment]
Thank you for sharing that .

You are Awesome
